# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Das Kopfkino"

# A description of your site for meta tag, search engine results.
description:

description_real: ë¨¸ë¦¿ì† ì •ë¦¬ì •ëˆì„ ìœ„í•´ ë§Œë“  ê³µê°„ì…ë‹ˆë‹¤.<br>ê°€ë” ìƒê°ë‚˜ë©´ ë†€ëŸ¬ì˜¤ì„¸ìš”.<br><a target="_self" href="https://taekwon.rsvp/ëª¸ê³¼-ë§ˆìŒì˜-ë³‘" target="_self"><u>ì—°ë½ ì•ˆë˜ì–´ ë¯¸ì•ˆí•©ë‹ˆë‹¤.</u></a> ì–¸ì  ê°„ ë§Œë‚˜ìš”.<br><br>íƒœê¶Œ <br><br><a target="_self" href="https://taekwon.rsvp/Background-Music-Not-Working" target="_self"><u>ğŸ“£ BGM ë°°ê²½ìŒì•…ì´ ë‚˜ì˜¤ì§€ ì•ŠëŠ”ë‹¤ë©´ ğŸ§</u></a>
# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://taekwon.rsvp"

# Favicon
favicon: /images/favicon-tae.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: #"G-3VHFE8W0N9" #"G-H8C1ZHNC63"

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about.html
  - text: Archive
    url: /archive.html
  - text: Survey
    url: /survey.html
  - text: Contact
    url: /contact.html #mailto:taekwon.rhee@gmail.com

# The shortname for your Disqus site to enable comments.
disqus: opakes-Kopfkino

# Colors
accent_color: "#011a5b" #"#004078" #"#760c0c"

# Site footer
footer:
  content: "&copy; 2024. <b>Tae Kwon Rhee</b> all rights reserved."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
